#1. 
SELECT * 
FROM FOOD_PRODUCT 
WHERE (SELECT MAX(PRICE)
        FROM FOOD_PRODUCT) = FOOD_PRODUCT.PRICE

#2.        
SELECT * 
FROM FOOD_PRODUCT 
WHERE FOOD_PRODUCT.PRICE IN (SELECT MAX(PRICE)
        FROM FOOD_PRODUCT)
