SELECT A.FLAVOR
FROM FIRST_HALF A JOIN (SELECT FLAVOR, INGREDIENT_TYPE FROM ICECREAM_INFO) B
ON A.FLAVOR = B.FLAVOR
WHERE A.TOTAL_ORDER >= 3000 AND B.INGREDIENT_TYPE = 'fruit_based'
ORDER BY A.TOTAL_ORDER DESC

/*
on - join이 실행되기전 
where - join 이 실행되고 난 후 의 조건절



*/
